---
- name: Ensure required packages are installed
  apt:
    name:
      - python3
      - python3-pip
      - python3.10-venv
      - docker.io
    state: present
    update_cache: yes

- name: Start and enable Docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Create agent directory
  file:
    path: "{{ venv_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create Python virtual environment
  command: python3 -m venv {{ venv_path }}
  args:
    creates: "{{ venv_path }}/bin/activate"

- name: Install integrate-ai CLI
  pip:
    name: integrate-ai
    virtualenv: "{{ venv_path }}"
    virtualenv_site_packages: no

- name: Install and register task runner agent
  command: >
    {{ venv_path }}/bin/iai onprem_node install
  environment:
    IAI_TOKEN: "{{ iai_token }}"
  args:
    creates: "{{ venv_path }}/ecsanywhere_output.txt"
  notify: restart ecs agent
